name: Deploy Newcon api

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 144.91.98.161 >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh root@144.91.98.161 << 'EOF'
          cd /home/newcon/newcon-api
          git pull origin main
          composer install
          php artisan route:cache
          sudo systemctl restart php8.2-fpm
        EOF